### PR TITLE
Stopped unnecessary customer account data from being shared

### PR DESCRIPTION
**Pull request by vrangr1**
Will need to pull changes from PR #73 after it's merged into master before this PR should be merged

### CODE REVIEW

**Comment by TestSubjector** [comment]
@mm12063 Do we keep the ```acc_active``` field in serialize and deserialize?

**Comment by mm12063** [comment]
Good idea re acc_active. We should probably hide that too. 
Can you try to get 100% code coverage please before merge?

**Comment by vrangr1** [comment]
Hiding acc_active in serialize and deserialize causes error in the following functions:
[test_activate_customer_account()](https://github.com/CSCI-GA-2820-FA22-003/customers/blob/master/tests/test_routes.py#L354)
[test_deactivate_customer_account()](https://github.com/CSCI-GA-2820-FA22-003/customers/blob/master/tests/test_routes.py#L388)
Any idea how to fix that @mm12063 ?

**Comment by vrangr1** [comment]
Also, @mm12063, do you know how to test for internal server error? That's the one missing from error_handlers.py in the coverage report?

**Pull request merged**
