### PR TITLE
Automatically generate Swagger docs using Flask-RESTPlus

### PR DESCRIPTION
**Pull request by TestSubjector**
* Create API model
* The documentation endpoint is on the /apidocs URL
* Closes issue #11 
* Clean up some now outdated tests
* Allows for refactoring issues to be worked on once this is closed

### CODE REVIEW

**Comment by mm12063** [comment]
There's a linting issue failing the test

**Comment by TestSubjector** [comment]
I've mentioned this in the Slack that this is due to modules that we'll need for refactoring (but are currently unused). I've asked whether I should comment them out for now.

**Comment by TestSubjector** [comment]
Commented out the unused modules as per the discussion in Slack.
They'll need to be commented back in when refactoring begins.

**Comment by vrangr1** [comment]
LGTM

**Pull request merged**
