### PR TITLE
Add method filter by city

### PR DESCRIPTION
**Pull request by KaterinPerdom**
# Description

Added a method to filter by city to model the customers
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## How Should This Be Tested?
Screenshot 2022-11-13 at 6 18 58 PM

You can use postman or thunder client as extension in vs code
1. You make a new request with new clients
2. You make a query where you indicate the name of the city (GET)

# Checklist:

- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mm12063 — CHANGES_REQUESTED** [review]
The updates to the routes are another issue.

**Comment by mm12063** [comment]
There are also some linting issues that need to be fixed. Run make lint locally to see the issues.

**Comment by KaterinPerdom** [comment]
@mm12063 
my PR have a lot of errors but what do you want to say with this -> The updates to the routes are another issue.

**Comment by mm12063** [comment]
Hi, the code for the routes.py and test_routes.py are still in the branch. These should be in a branch related to issue #45. The branch is also still failing to pass the linting tests.

**Comment by mm12063** [comment]
Sorry, just saw your update. You need to cut the routes code and save it locally. Then once this branch is passing tests and merged into master, create a new branch and put the routes code in there for a PR.

**Pull request closed without merging**
