### PR TITLE
Search by City Irrespective of Case Styles

### PR DESCRIPTION
**Pull request by vrangr1**

### CODE REVIEW

**Comment by vrangr1** [comment]
Note that I am doing this by storing city in Title case when creating or updating a customer, and, as such, querying for an input city by setting it in Title case and then searching.

**Comment by KaterinPerdom** [comment]
@vrangr1 

Its not working 
Screenshot 2022-11-30 at 11 20 01 AM
Screenshot 2022-11-30 at 11 21 54 AM

**Comment by TestSubjector** [comment]
@KaterinPerdom 
This PR Seems to be working for me though (and the tests are passing)

A1
A2

**Comment by TestSubjector** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/1f33ebc4-d047-48d9-93b4-8bb624095178?env_id=ibm:yp:us-south "nyu-devops-customers"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/91c20a20-6bcd-4ec6-a1af-2eafe6efb5ec "customers") deployed [customers](https://github.com/CSCI-GA-2820-FA22-003/customers/releases/tag/deploy-nyu-devops-20221130-185106 "deploy-nyu-devops-20221130-185106") to [nyu-devops](https://cloud.ibm.com/kubernetes/clusters/cdoth5bf0ihna4ug0qtg/overview "There was a problem retrieving the space name"), including commit 5eca86a2173db25737e874b593816f60d9fb2745

**Pull request merged**
